[build-system]
requires = ["setuptools"]

[project]
name = "tdfextractor"
dynamic = ["version"]
description = "extract ms2/mgf files from bruker d folders"
authors = [
    {name = "Patrick Garrett", email = "pgarrett@scripps.edu"},
]
dependencies = [
    "tdfpy>=1.0.2",
    "serenipy>=0.4.0",
    "psims>=1.3.6",
    "numpy",
    "pandas",
    "tqdm",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
readme = "README.md"
requires-python = ">=3.12"
license = {file = "LICENSE"}

[project.scripts]
mgf-extractor = "tdfextractor.mgf_exctractor:main"
ms2-extractor = "tdfextractor.ms2_extractor:main"
mzml-extractor = "tdfextractor.mzml_extractor:main"
mgf-ex = "tdfextractor.mgf_exctractor:main"
ms2-ex = "tdfextractor.ms2_extractor:main"
mzml-ex = "tdfextractor.mzml_extractor:main"


[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "tdfextractor.__version__"}